### ISSUE TITLE
GUI<->Server via GBit Ethernet

### ISSUE THREAD

**Issue by MaZderMind** [timvideos/gst-switch#111]
Currently the GUI and the Server communicate raw Frames via TCP. In theory this would work over GBit Ethernet, too, if not GBit Ethernet was to slow to carry RAW Frames (for reference: HD SDI is 3 GBit/s for 1080p).

We would like to have the server run headless on a machine with plenty of CPU Power and the GUI on one a Notebook with a display. We do this with DVSwitch the same way (DVSWitch running on the Notebook, Sources and Sinks on the Encoder-Computer).

For this the transport channels between Server and GUI would need to be encoded with some I-Frame Only encoder that can run in Realtime. Maybe MPEG2? Maybe only send a scaled version to the GUI (doesn't need to be full 1080p for the preview images at least)

**Comment by duzy** [comment]
The preview images are better scaled before sending to the GUI client (I
don't remember if it was in this way) for saving network and men
bandwidths. But this will require powerful computing ability on the server
side. When I was doing it, my old ThinkPad T410 was not able to handle such
scale of computing. The best way will be enabling the computing power of
GPU -- if this is possible with some gst element.

When I was doing it, I was confronting two major issues, one is that the
GST messages are ref-counted and the management of them are difficult when
complex nodes are involved, and that causes message-leak somehow and hard
to be discovered. Lucky gst has a save-back way to solve it.

The other issue is about balancing system bandwidth and the computing
ability. This could of cause be solved by putting best hardware on it. But
when not, it would be the most significant things to be done to make it
really time.

**Comment by a-tze** [comment]
Scaling should not be an issue, if using fixed scale factor of 2 or 4 and maybe dropping interpolation. Even with basic bilinear interpolation, scaling by a fixed factor of 2 or 4 doesn't result in heavy cpu load in my experience. 
The codec was a more interesting question, but if the image is downscaled to HD/2 or even HD/4 actually RAW could be used again, but applying MJPEG, MPEG-2 or even FFV1 could still be a good idea. If that is configurable for the setup, everyone could figure out the best setting for the current use case.

I would like to throw in a third option on reducing the bandwidth, that does not consume very much CPU: reducing framerate. For preview 5 fps could be enough, or even better because you can inspect details of the image that would otherwise blur away in the motion, e.g. if the cam is focussed correctly. Downscaling the preview would prevent the operator from seeing such errors.

**Comment by duzy** [comment]
I guess scaling should had been done optimized a lot, by I'm not sure how's
the performance once the memory went critical low.

It's quite possible to make all pipelines of the server configurable. Thus
everyone playing with it could be able to experiment there favorite
pipelines.

And I would agree that reducing the frame rate for previews could be a good
idea.

**Comment by thaytan** [comment]
With suitably specced server machines we could look at doing more operations on the GPU - such as scaling, although it might require newer GStreamer for that.
