### ISSUE TITLE
Python API should support Python 3

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#139]
- Try running `py2to3` and see what breaks. 
- Check the dependencies support Python 3.

I think we should probably end up with a Python 3 code base and then use `py3to2` to keep support Python 2 support. 

Might want to do https://github.com/timvideos/gst-switch/issues/128 first.

**Comment by mithro** [comment]
@MaZderMind

**Comment by mithro** [comment]
https://wiki.python.org/moin/3to2

**Comment by mithro** [comment]
From http://ondrejcertik.blogspot.co.nz/2013/08/how-to-support-both-python-2-and-3.html
 * Port your project to Python 2.6.
 * Turn on the Py3k warnings mode.
 * Test and edit until no warnings remain.
 * Use the 2to3 tool to convert this source code to 3.0 syntax. Do not manually edit the output!
 * Test the converted source code under 3.0.
 * If problems are found, make corrections to the 2.6 version of the source code and go back to step 3.
 * When it's time to release, release separate 2.6 and 3.0 tarballs (or whatever archive form you use for releases).

http://python-future.org/overview.html#automatic-translation

**Comment by MaZderMind** [comment]
I don't think supporting two platforms makes things easier. It gives two targets to test, two kinds of bux to fix and one question more to ask in bug-reports.

Developing in 2.6 has even more disadvantages: It does mean not to take advantages of the things fixed in python3, for example you can't rely on string operations being unicode save. So you have no win but more work.

I'm for going 100% python3, Your Target-Release Ubuntu 14.04 already has python3.4 abd I don't see any lib we're using not being supported by python3.

**Comment by leesdolphin** [comment]
It is possible to have the same code base work with both Python 2 and Python 3. I think this should be our target. It might be a case that we need to wrap some stuff in the equivalent of `if ON_PYTHON_3:`; but that would be better than 2 separate code bases.

So Twisted is a Python 2 project; but they are porting to Python 3 using this method. [Read More](http://twistedmatrix.com/trac/wiki/Plan/Python3) on their wiki.

**Comment by mithro** [comment]
My thought is that;
 * We convert to Python 3.
 * Add the 3to2 "automagical" conversion stuff in setup.py
 * Reevaluate if the "automagical" bit fails.
