### ISSUE TITLE
Make recording pipeline a command line argument

### ISSUE THREAD

**Issue by mithro** [timvideos/gst-switch#59]
This would allow the recording format to be specified by the user rather than hard coded.

It does have the downside that you could use a _bad_ recording format which means your recording end up sucking.

**Comment by MaZderMind** [comment]
I can see two solutions for that:

1) We could have a default recording system in the core (which is using the cut buttons in the ui and such) but a way to turn that of via commandline. This would also turn of all recording related stuff in the ui.

A custom recoring pipeline could be connected via a tcpclientsink. At the @voc we're using a segmented recording technique which records 24h a day and we don't want a user from the ui to be able to mess with the recording. We would then just turn of the recoding and connect our segmentation-process to the adequate tcp port.

2) make parts of the gstreamer pipeline configurable (as gstreamer strings) which could allow for great flexibility but with a much greater error-proneness (because then custom quasi-code would be running in the server process)
